#!/usr/bin/env php
<?php

use phpDocumentor\AutoloaderLocator;
use phpDocumentor\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

set_time_limit(0);

$_PHPDOC_EXTENSIONS_DIRS = include '/usr/lib/phpdocumentor/src/extension-finder/Finder.php';
require '/usr/lib/phpdocumentor/src/phpDocumentor/AutoloaderLocator.php';
$loader = AutoloaderLocator::autoload();
$application = new Application($_PHPDOC_EXTENSIONS_DIRS ?? []);
$application->run();
